import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Providers } from "./providers";
import localFont from "next/font/local";

const Tilt_Warp = localFont({
  src: "../assets/fonts/TiltWarp.ttf",
  variable: "--font-tiltwarp",
});

const Cocogoose = localFont({
  src: "../assets/fonts/Cocogoose-Darkmode.ttf",
  variable: "--font-cocogoose",
});

export const metadata: Metadata = {
  title: "Urbik - Encotrá tu lugar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${Tilt_Warp.variable} ${Cocogoose.variable}`}>
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
