import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/navbar/Wrapper";
import {Providers} from "./providers";



export const metadata: Metadata = {
  title: "Urbik - Encotrá tu lugar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavbarWrapper/> 
          {children}
        </Providers>
      </body>
    </html>
  );
}